name = "Aero Pack"
author = "Master_Bw3"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc21c3c9ad5cea53b18c40f9e4ef6f93732a90c8cd46131bb92bb264ea289375"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
