name = "Aero Pack"
author = "Master_Bw3"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0cfeac7dcbf37e890bd44f851b7b0c388b96395f54ce50b53621d7e7bf129c9e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
