name = "Aero Pack"
author = "Master_Bw3"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e12db89036944f29f1085fdf3e2512e65b4cc9e4b811971338729af24cc7a89"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
