! Put your rules here in the format:
! old_biome > new_biome
! 
! Examples (remove ! in front of one to activate it):
! minecraft:dark_forest > minecraft:cherry_grove
! #minecraft:is_forest > minecraft:desert
! #terralith:skylands > null

[minecraft:overworld]
biomesoplenty:cold_desert
biomesoplenty:coniferous_forest
biomesoplenty:crag
biomesoplenty:dead_forest
biomesoplenty:aspen_glade
biomesoplenty:auroral_garden
biomesoplenty:bayou
biomesoplenty:bog
biomesoplenty:dryland
biomesoplenty:dune_beach
biomesoplenty:field
biomesoplenty:fir_clearing
biomesoplenty:floodplain
biomesoplenty:forested_field
biomesoplenty:fungal_jungle
biomesoplenty:glowing_grotto
biomesoplenty:grassland
biomesoplenty:gravel_beach
biomesoplenty:highland
biomesoplenty:hot_springs
biomesoplenty:jacaranda_glade
biomesoplenty:jade_cliffs
biomesoplenty:lavender_field
biomesoplenty:lush_desert
biomesoplenty:lush_savanna
biomesoplenty:maple_woods
biomesoplenty:marsh
biomesoplenty:mediterranean_forest
biomesoplenty:moor
biomesoplenty:muskeg
biomesoplenty:mystic_grove
biomesoplenty:old_growth_dead_forest
biomesoplenty:old_growth_woodland
biomesoplenty:ominous_woods
biomesoplenty:orchard
biomesoplenty:origin_valley
biomesoplenty:overgrown_greens
biomesoplenty:pasture
biomesoplenty:prairie
biomesoplenty:pumpkin_patch
biomesoplenty:rainforest
biomesoplenty:redwood_forest
biomesoplenty:rocky_rainforest
biomesoplenty:rocky_shrubland
biomesoplenty:scrubland
biomesoplenty:seasonal_forest
biomesoplenty:shrubland
biomesoplenty:snowblossom_grove
biomesoplenty:snowy_coniferous_forest
biomesoplenty:snowy_fir_clearing
biomesoplenty:snowy_maple_woods
biomesoplenty:spider_nest
biomesoplenty:tropics
biomesoplenty:tundra
biomesoplenty:volcanic_plains
biomesoplenty:volcano
biomesoplenty:wasteland
biomesoplenty:wasteland_steppe
biomesoplenty:wetland
biomesoplenty:wintry_origin_valley
biomesoplenty:woodland
minecraft:badlands
minecraft:bamboo_jungle
minecraft:beach
minecraft:birch_forest
minecraft:cherry_grove
minecraft:cold_ocean
minecraft:dark_forest
minecraft:deep_cold_ocean
minecraft:deep_dark
minecraft:deep_frozen_ocean
minecraft:deep_lukewarm_ocean
minecraft:deep_ocean
minecraft:desert
minecraft:dripstone_caves
minecraft:eroded_badlands
minecraft:flower_forest
minecraft:forest
minecraft:frozen_ocean
minecraft:frozen_peaks
minecraft:meadow
minecraft:mushroom_fields
minecraft:ocean
minecraft:old_growth_birch_forest
minecraft:old_growth_pine_taiga
minecraft:old_growth_spruce_taiga
minecraft:plains
minecraft:river
minecraft:frozen_river
minecraft:grove
minecraft:ice_spikes
minecraft:jagged_peaks
minecraft:jungle
minecraft:lukewarm_ocean
minecraft:lush_caves
minecraft:mangrove_swamp
minecraft:savanna
minecraft:savanna_plateau
minecraft:snowy_beach
minecraft:snowy_plains
minecraft:snowy_slopes
minecraft:snowy_taiga
minecraft:sparse_jungle
minecraft:stony_peaks
minecraft:stony_shore
minecraft:sunflower_plains
minecraft:swamp
minecraft:taiga
minecraft:warm_ocean
minecraft:windswept_forest
minecraft:windswept_gravelly_hills
minecraft:windswept_hills
minecraft:windswept_savanna
minecraft:wooded_badlands
natures_spirit:alpine_clearings
natures_spirit:alpine_highlands
natures_spirit:arid_highlands
natures_spirit:arid_savanna
natures_spirit:aspen_forest
natures_spirit:bamboo_wetlands
natures_spirit:blooming_dunes
natures_spirit:blooming_highlands
natures_spirit:blooming_sugi_forest
natures_spirit:boreal_taiga
natures_spirit:carnation_fields
natures_spirit:cedar_thicket
natures_spirit:chaparral
natures_spirit:coniferous_covert
natures_spirit:cypress_fields
natures_spirit:drylands
natures_spirit:dusty_slopes
natures_spirit:fir_forest
natures_spirit:floral_ridges
natures_spirit:flowering_shrubland
natures_spirit:golden_wilds
natures_spirit:heather_fields
natures_spirit:lavender_fields
natures_spirit:lively_dunes
natures_spirit:maple_woodlands
natures_spirit:marigold_meadows
natures_spirit:marsh
natures_spirit:oak_savanna
natures_spirit:prairie
natures_spirit:red_peaks
natures_spirit:redwood_forest
natures_spirit:scorched_dunes
natures_spirit:shrubby_highlands
natures_spirit:shrubland
natures_spirit:sleeted_slopes
natures_spirit:snowcapped_red_peaks
natures_spirit:snowy_fir_forest
natures_spirit:sparse_tropical_woods
natures_spirit:stratified_desert
natures_spirit:sugi_forest
natures_spirit:tropical_basin
natures_spirit:tropical_shores
natures_spirit:tropical_woods
natures_spirit:tundra
natures_spirit:white_cliffs
natures_spirit:windswept_sugi_forest
natures_spirit:wisteria_forest
natures_spirit:wooded_drylands
natures_spirit:woody_highlands
natures_spirit:xeric_plains
regions_unexplored:alpha_grove
regions_unexplored:ancient_delta
regions_unexplored:arid_mountains
regions_unexplored:ashen_woodland
regions_unexplored:autumnal_maple_forest
regions_unexplored:bamboo_forest
regions_unexplored:baobab_savanna
regions_unexplored:barley_fields
regions_unexplored:bayou
regions_unexplored:bioshroom_caves
regions_unexplored:blackwood_taiga
regions_unexplored:boreal_taiga
regions_unexplored:chalk_cliffs
regions_unexplored:clover_plains
regions_unexplored:cold_boreal_taiga
regions_unexplored:cold_deciduous_forest
regions_unexplored:cold_river
regions_unexplored:deciduous_forest
regions_unexplored:dry_bushland
regions_unexplored:eucalyptus_forest
regions_unexplored:fen
regions_unexplored:flower_fields
regions_unexplored:frozen_pine_taiga
regions_unexplored:frozen_tundra
regions_unexplored:fungal_fen
regions_unexplored:golden_boreal_taiga
regions_unexplored:grassland
regions_unexplored:grassy_beach
regions_unexplored:gravel_beach
regions_unexplored:highland_fields
regions_unexplored:hyacinth_deeps
regions_unexplored:icy_heights
regions_unexplored:joshua_desert
regions_unexplored:magnolia_woodland
regions_unexplored:maple_forest
regions_unexplored:marsh
regions_unexplored:mauve_hills
regions_unexplored:mountains
regions_unexplored:muddy_river
regions_unexplored:old_growth_bayou
regions_unexplored:orchard
regions_unexplored:outback
regions_unexplored:pine_slopes
regions_unexplored:pine_taiga
regions_unexplored:poppy_fields
regions_unexplored:prairie
regions_unexplored:prismachasm
regions_unexplored:pumpkin_fields
regions_unexplored:rainforest
regions_unexplored:redstone_caves
regions_unexplored:redwoods
regions_unexplored:rocky_meadow
regions_unexplored:rocky_reef
regions_unexplored:saguaro_desert
regions_unexplored:scorching_caves
regions_unexplored:shrubland
regions_unexplored:silver_birch_forest
regions_unexplored:sparse_rainforest
regions_unexplored:sparse_redwoods
regions_unexplored:spires
regions_unexplored:steppe
regions_unexplored:temperate_grove
regions_unexplored:towering_cliffs
regions_unexplored:tropical_river
regions_unexplored:tropics
regions_unexplored:willow_forest